{"num_games": 100, "student_agent_wins": [0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1], "random_agent_wins": [1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0], "student_agent_win_count": 29, "random_agent_win_count": 71, "student_agent_win_percentage": 0.29, "random_agent_win_percentage": 0.71, "student_agent_time_taken": 0.003488917350769043, "random_agent_time_taken": 0.0029484200477600097, "run_info": [{"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.002118825912475586, "random_agent_time": 0.0006999969482421875, "board_size": 6, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.002663135528564453, "random_agent_time": 0.0020940303802490234, "board_size": 6, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.0027692317962646484, "random_agent_time": 0.0024852752685546875, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002125978469848633, "random_agent_time": 0.001878976821899414, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.004947185516357422, "random_agent_time": 0.004713535308837891, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.002584695816040039, "random_agent_time": 0.0034017562866210938, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0043756961822509766, "random_agent_time": 0.0016863346099853516, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.002774953842163086, "random_agent_time": 0.0021665096282958984, "board_size": 6, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0022873878479003906, "random_agent_time": 0.002185344696044922, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.0035812854766845703, "random_agent_time": 0.004114866256713867, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.0031545162200927734, "random_agent_time": 0.002830028533935547, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.00762176513671875, "random_agent_time": 0.007209300994873047, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0020799636840820312, "random_agent_time": 0.0018062591552734375, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.0003478527069091797, "random_agent_time": 0.0009672641754150391, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.003438711166381836, "random_agent_time": 0.0008883476257324219, "board_size": 6, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0024285316467285156, "random_agent_time": 0.0017299652099609375, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.005641937255859375, "random_agent_time": 0.0018453598022460938, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 80, "random_agent_score": 1, "student_agent_time": 0.004498958587646484, "random_agent_time": 0.005104541778564453, "board_size": 9, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 5] to [3 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.0020532608032226562, "random_agent_time": 0.003843069076538086, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.00030922889709472656, "random_agent_time": 0.0026123523712158203, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004308223724365234, "random_agent_time": 0.002123117446899414, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.008645772933959961, "random_agent_time": 0.006118297576904297, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0022296905517578125, "random_agent_time": 0.002192258834838867, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.0015327930450439453, "random_agent_time": 0.0006487369537353516, "board_size": 6, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0031158924102783203, "random_agent_time": 0.0028388500213623047, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.00415492057800293, "random_agent_time": 0.002775907516479492, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003744840621948242, "random_agent_time": 0.0025353431701660156, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0030107498168945312, "random_agent_time": 0.0018477439880371094, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.003862142562866211, "random_agent_time": 0.002347230911254883, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.0072727203369140625, "random_agent_time": 0.007287740707397461, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.00036907196044921875, "random_agent_time": 0.0007975101470947266, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0022363662719726562, "random_agent_time": 0.0019736289978027344, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.0017261505126953125, "random_agent_time": 0.0006995201110839844, "board_size": 6, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.0028731822967529297, "random_agent_time": 0.0018451213836669922, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.006144046783447266, "random_agent_time": 0.0021011829376220703, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.00558161735534668, "random_agent_time": 0.006124973297119141, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.0033419132232666016, "random_agent_time": 0.002311229705810547, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.0026907920837402344, "random_agent_time": 0.002443075180053711, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.00030040740966796875, "random_agent_time": 0.0008258819580078125, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.0017554759979248047, "random_agent_time": 0.003162860870361328, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004293203353881836, "random_agent_time": 0.00550389289855957, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.007553577423095703, "random_agent_time": 0.0075225830078125, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.0020766258239746094, "random_agent_time": 0.0006363391876220703, "board_size": 6, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.00234222412109375, "random_agent_time": 0.002529621124267578, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004167795181274414, "random_agent_time": 0.005414009094238281, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0033376216888427734, "random_agent_time": 0.002296924591064453, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.0035316944122314453, "random_agent_time": 0.0029060840606689453, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.004364490509033203, "random_agent_time": 0.002622365951538086, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.0020530223846435547, "random_agent_time": 0.0019712448120117188, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.002213716506958008, "random_agent_time": 0.0043201446533203125, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.0030336380004882812, "random_agent_time": 0.004514217376708984, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.0002636909484863281, "random_agent_time": 0.0006971359252929688, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004133939743041992, "random_agent_time": 0.0018815994262695312, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0025670528411865234, "random_agent_time": 0.0026106834411621094, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.0003581047058105469, "random_agent_time": 0.0012862682342529297, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004106283187866211, "random_agent_time": 0.0021359920501708984, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0025441646575927734, "random_agent_time": 0.0021877288818359375, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.0056226253509521484, "random_agent_time": 0.0062901973724365234, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.002350330352783203, "random_agent_time": 0.002095937728881836, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002398967742919922, "random_agent_time": 0.002428770065307617, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.00394892692565918, "random_agent_time": 0.003172159194946289, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.0013630390167236328, "random_agent_time": 0.0008480548858642578, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0026476383209228516, "random_agent_time": 0.0029981136322021484, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 120, "random_agent_score": 1, "student_agent_time": 0.002172231674194336, "random_agent_time": 0.002401113510131836, "board_size": 11, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [9 3] to [9 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004060268402099609, "random_agent_time": 0.0021142959594726562, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.004535198211669922, "random_agent_time": 0.005735158920288086, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004584074020385742, "random_agent_time": 0.002196073532104492, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.004626035690307617, "random_agent_time": 0.0029599666595458984, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002325773239135742, "random_agent_time": 0.002864837646484375, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0035963058471679688, "random_agent_time": 0.002552509307861328, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.005665302276611328, "random_agent_time": 0.0028676986694335938, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0034949779510498047, "random_agent_time": 0.002794027328491211, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.003582000732421875, "random_agent_time": 0.0025267601013183594, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0025043487548828125, "random_agent_time": 0.0019068717956542969, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 79, "student_agent_time": 0.004364728927612305, "random_agent_time": 0.001987457275390625, "board_size": 9, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 3] to [5 3] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.0073549747467041016, "random_agent_time": 0.006958484649658203, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002667665481567383, "random_agent_time": 0.0027968883514404297, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.00031065940856933594, "random_agent_time": 0.0008869171142578125, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0030252933502197266, "random_agent_time": 0.0024869441986083984, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 99, "random_agent_score": 1, "student_agent_time": 0.0003662109375, "random_agent_time": 0.0009665489196777344, "board_size": 10, "swap_players": true, "run_out": ""}, {"student_agent_score": 1, "random_agent_score": 35, "student_agent_time": 0.004098176956176758, "random_agent_time": 0.0007712841033935547, "board_size": 6, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 3\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.004172801971435547, "random_agent_time": 0.0024123191833496094, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.005326032638549805, "random_agent_time": 0.0032689571380615234, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 2, "random_agent_score": 98, "student_agent_time": 0.0045011043548583984, "random_agent_time": 0.006256818771362305, "board_size": 10, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 5] to [7 5] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 6] to [6 6] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [7 8] to [7 8] and put barrier at 0, with max steps = 5\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0033843517303466797, "random_agent_time": 0.004236936569213867, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0026895999908447266, "random_agent_time": 0.002304553985595703, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0056302547454833984, "random_agent_time": 0.0045604705810546875, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 63, "random_agent_score": 1, "student_agent_time": 0.002221822738647461, "random_agent_time": 0.0021355152130126953, "board_size": 8, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 5] to [5 5] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0026857852935791016, "random_agent_time": 0.0024831295013427734, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.002365589141845703, "random_agent_time": 0.0025167465209960938, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.008472204208374023, "random_agent_time": 0.00934290885925293, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 63, "student_agent_time": 0.0033402442932128906, "random_agent_time": 0.0023436546325683594, "board_size": 8, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 2] to [2 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 1] to [3 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 0] to [3 0] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 1] to [6 1] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0055005550384521484, "random_agent_time": 0.003223419189453125, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003517627716064453, "random_agent_time": 0.0025267601013183594, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0041353702545166016, "random_agent_time": 0.0021920204162597656, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0045773983001708984, "random_agent_time": 0.002176523208618164, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.0027132034301757812, "random_agent_time": 0.002978086471557617, "board_size": 7, "swap_players": true, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [2 3] to [2 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 1, "random_agent_score": 48, "student_agent_time": 0.003884553909301758, "random_agent_time": 0.00203704833984375, "board_size": 7, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 2] to [4 2] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 3] to [4 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [5 4] to [5 4] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [6 3] to [6 3] and put barrier at 0, with max steps = 4\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.00681304931640625, "random_agent_time": 0.006890535354614258, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}, {"student_agent_score": 117, "random_agent_score": 1, "student_agent_time": 0.007653713226318359, "random_agent_time": 0.007048368453979492, "board_size": 11, "swap_players": false, "run_out": "An exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 7] to [1 7] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 8] to [1 8] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [1 6] to [1 6] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 3] to [3 3] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [3 4] to [3 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\nAn exception raised. The traceback is as follows:\nTraceback (most recent call last):\n  File \"/home/ml/users/ksinha4/mlp/comp424_final_project/submissions/comp424mcgill/final-project-joystick-fighters/world.py\", line 310, in step\n    raise ValueError(\nValueError: [INVALID:STEP] Not a valid step from [4 4] to [4 4] and put barrier at 0, with max steps = 6\n\nExecute Random Walk!\n"}]}